# TEMPORARY (#621): record font diagnostics inside the running ECS container and
# publish them under the app's www/diag621/ folder. Prints env var NAMES only.
diag621 <- function(tag) {
  outdir <- file.path(system.file("app/www", package = "EJAM"), "diag621")
  dir.create(outdir, showWarnings = FALSE, recursive = TRUE)
  f <- file.path(outdir, paste0("diag_", tag, ".txt"))
  con <- file(f, "w"); on.exit(close(con))
  w <- function(...) writeLines(paste0(...), con)
  sh <- function(cmd) paste(tryCatch(system(cmd, intern = TRUE), error = function(e) conditionMessage(e)), collapse = "\n")
  w("time: ", format(Sys.time()), "  tag: ", tag)
  w("id: ", sh("id")); w("ulimit -n: ", sh("ulimit -n")); w("nproc: ", sh("nproc"))
  w("uname: ", sh("uname -a"))
  w("fd count: ", length(list.files("/proc/self/fd")))
  keep <- c("HOME", "USER", "LANG", "LC_ALL", "TMPDIR", "XDG_CACHE_HOME", "XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_RUNTIME_DIR", "FONTCONFIG_FILE", "FONTCONFIG_PATH", "R_HOME")
  w("env names: ", paste(sort(names(Sys.getenv())), collapse = " "))
  for (k in keep) w("env ", k, "=", Sys.getenv(k, "<unset>"))
  w("fc-match sans: ", sh("fc-match sans"))
  w("fc-list count: ", sh("fc-list | wc -l"))
  w("fc cache dirs: ", sh("ls -la /var/cache/fontconfig | head -5; ls -la ~/.cache/fontconfig 2>&1 | head -5"))
  w("liberation file: ", sh("ls -la /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf; head -c 4 /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf | od -c | head -1"))
  w("mounts: ", sh("cat /proc/mounts | head -30"))
  w("df: ", sh("df -h / /tmp /dev/shm 2>&1"))
  m <- tryCatch(systemfonts::match_fonts("sans"), error = function(e) conditionMessage(e))
  w("systemfonts::match_fonts('sans'): ", paste(capture.output(print(m)), collapse = "\n"))
  s <- tryCatch(textshaping::shape_text("Residential Alpha Omega 0.5")$shape, error = function(e) NULL)
  if (!is.null(s)) w("shape_text: notdef=", sum(s$index == 0), " of ", nrow(s), "; fonts: ", paste(unique(basename(s$font_path)), collapse = ", "))
  p <- ggplot2::ggplot(data.frame(x = c("Alpha", "Omega"), y = 1:2), ggplot2::aes(x, y)) + ggplot2::geom_col() +
    ggplot2::labs(title = "Residential Populations Compared to US Overall") + ggplot2::theme_bw()
  r1 <- try({ ragg::agg_png(file.path(outdir, paste0("ragg_", tag, ".png")), 700, 450); print(p); dev.off() })
  r2 <- try({ png(file.path(outdir, paste0("cairo_", tag, ".png")), 700, 450, type = "cairo"); print(p); dev.off() })
  w("ragg ok: ", !inherits(r1, "try-error"), "  cairo ok: ", !inherits(r2, "try-error"))
  w("sessionInfo:\n", paste(capture.output(sessionInfo()), collapse = "\n"))
  invisible(f)
}
try(diag621("start"))
later::later(function() try(diag621("after120s")), 120)
