---
title: "&#32;"
output: 
  html_document:
    css: ["communityreport.css"]
params:
  output_df: NA
  analysis_title: NA
  totalpop: NA
  locationstr: NA
  include_ejindexes: TRUE
  in_shiny: FALSE
  filename: NULL
  map: NULL
  report_plot: NULL
  report_plot_state: NULL
  report_title: NULL
  logo_path: NULL
  logo_html: NULL
  footer_version_number: NULL
  footer_date: NULL
  footer_text: NULL
  footer_html: NULL
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r build_barplot_report}
if (!exists("blockgroupstats")) {library(EJAM)} # to use installed version only if not already attached
# library(EJAM) # for development purposes, might be better to allow it to use the loaded version from load_all() if that is already available, rather than always/only using the installed version here ***

build_barplot_report(
  
  logo_path      = params$logo_path,
  logo_html      = params$logo_html,
  report_title   = params$report_title,
  analysis_title = params$analysis_title,
  locationstr    = params$locationstr,
  totalpop       = params$totalpop,
  
  # include_ejindexes = params$include_ejindexes,
  in_shiny       = params$in_shiny,
  filename       = params$filename
)
```

```{r map, fig.align='center'}
## skip the map

# params$map

```

```{r space1}
HTML('<br>')
```

```{r report_plot, out.width='90%', fig.align='center'}

params$report_plot

```

```{r space2}
HTML('<br>')
```

```{r report_plot_state, out.width='90%', fig.align='center'}

params$report_plot_state

```

```{r footer_with_version_and_date}
# To make footer blank (no text), pass "" for footer_text or footer_html.
EJAM:::generate_report_footer(
  footer_version_number = params$footer_version_number,
  footer_date = params$footer_date,
  footer_text = params$footer_text,
  footer_html = params$footer_html
)

```
