---
title: "&#32;"
output:
  html_document:
    css: ["communityreport.css"]
params:
  community_html: NULL
  map: NULL
  map_png_path: NULL
  plot: NULL
  footer_version_number: NULL
  footer_date: NULL
  footer_text: NULL
  footer_html: NULL
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# remember params can be defined using r code too: https://r4ds.had.co.nz/r-markdown.html#parameters
## like, 
## params:
##    rundate: !r  lubridate::ymd_hms("2015-01-01 12:30:00")
## client side ideally should provide footer_date to ensure user's timezone is used to determine today's date
```


```{r report_html, results='asis'}

#   Header (logo, report title, analysis title)
# + Tables of data

shiny::HTML(params$community_html)   # from build_community_report()
```

```{r map_section, echo=FALSE}
#
if (!is.null(params$map_png_path) && nzchar(params$map_png_path) && file.exists(params$map_png_path)) {
  # Static PNG snapshot (used for PDF output); embed inline so the self-contained HTML
  # can be passed to chrome_print() without needing external file access.
  htmltools::tagList(
    htmltools::tags$section(
      class = "report-section report-map-section",
      htmltools::tags$img(
        src = knitr::image_uri(params$map_png_path),
        alt = "Map",
        style = "width: 100%; max-width: 100%;"
      )
    )
  )
} else if (!(is.null(params$map) || anyNA(params$map) || length(params$map) == 0)) {
  htmltools::tagList(
    htmltools::tags$section(
      class = "report-section report-map-section",
      params$map
    )
  )
}
```

```{r plot, results='asis', fig.align='center', out.width='100%'}
#
cat('<section class="report-section report-plot-section">')
print(params$plot)
cat('</section>')
```

```{r footer, fig.align='center', out.width='100%'}
# To make footer blank (no text), pass "" for footer_text or footer_html.
#
EJAM:::generate_report_footer(
  footer_version_number = params$footer_version_number,
  footer_date = params$footer_date,
  footer_text = params$footer_text,
  footer_html = params$footer_html
)

```
