---
title: "&#32;"
output: 
  html_document:
    css: ["communityreport.css"]
params:
  logo_path: NULL
  logo_html: NULL
  report_title: NULL
  analysis_title: NA
  locationstr: NA
  totalpop: NA
  output_df: NA
  include_ejindexes: TRUE
  show_ratios_in_report: NA
  extratable_show_ratios_in_report: NA
  extratable_title: NA
  extratable_title_top_row: NA
  extratable_list_of_sections: NA
  extratable_hide_missing_rows_for: NA
  in_shiny: FALSE
  filename: NULL
  map: NULL
  summary_plot: NULL
  footer_version_number: NULL
  footer_date: NULL
  footer_text: NULL
  footer_html: NULL
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# remember params can be defined using r code too: https://r4ds.had.co.nz/r-markdown.html#parameters
## like, 
## params:
##    rundate: !r  lubridate::ymd_hms("2015-01-01 12:30:00")
## client side ideally should provide footer_date to ensure user's timezone is used to determine today's date
```


```{r build_community_report}

#   Header (logo, report title, analysis title)
# + Tables of data

build_community_report(
  
  logo_path      = params$logo_path,
  logo_html      = params$logo_html,
  report_title   = params$report_title,
  analysis_title = params$analysis_title,
  locationstr    = params$locationstr,
  totalpop       = params$totalpop,
  
  output_df      = params$output_df,
  include_ejindexes                = params$include_ejindexes,
  show_ratios_in_report            = params$show_ratios_in_report,
  extratable_show_ratios_in_report = params$extratable_show_ratios_in_report,
  extratable_title                 = params$extratable_title,
  extratable_title_top_row         = params$extratable_title_top_row,
  extratable_list_of_sections      = params$extratable_list_of_sections, # just use default
  extratable_hide_missing_rows_for = params$extratable_hide_missing_rows_for, # just use default
  
  in_shiny     = params$in_shiny,
  filename     = params$filename
)
```

```{r map, fig.align='center'}
#
if (!(is.null(params$map) || anyNA(params$map) || length(params$map) == 0)) {
  #
  params$map
}
```

```{r summary_plot, out.width='90%', fig.align='center'}
#
params$summary_plot
```

```{r footer_with_version_and_date}
# To make footer blank (no text), pass "" for footer_text or footer_html.
#
EJAM:::generate_report_footer(
  footer_version_number = params$footer_version_number,
  footer_date = params$footer_date, # should provide footer_date to ensure user's timezone is used to determine today's date
  footer_text = params$footer_text,
  footer_html = params$footer_html
)

```
