########################################################################### #

## Function that contains the actual testing steps that check web app UI functionality

## This gets called by each relevant test-*.R file.

## Those test-*.R files can get run by various starting points:


########################################################################### #

## setup.R will already have done this:
# library(EJAM) # and anyway, shinytest2::AppDriver() by default uses app.R which does library(EJAM) if needed, before it uses ejamapp()
# library(shinytest2)

cat("getting the function 'shinytest2_webapp_functionality()' \n")
cat("see also the article/vignette built from dev-run-shinytests.Rmd at \n")
cat(paste0(EJAM::url_package("docs"), "/articles/dev-run-shinytests.html \n"))
# browseURL(paste0(EJAM::url_package("docs"), "/articles/dev-run-shinytests.html"))

unlink("tests/shinytestlog.txt") # deletes this file if it exists
# see also "tests/testthat/testthat.R"

## To use this function, indirectly, in RStudio you could do
# shinytest2::test_app(".", filter = "functionality", check_setup = FALSE)
# but that is getting deprecated by shinytest2 as an approach?
## or should be able to do
# library(EJAM)
# x = EJAM:::test_ejam(ask=F, run_these="webapp")
## and
# directly test one category interactively using
# shinytest2_webapp_functionality(test_category = "latlon")
########################################################################### #
########################################################################### #

shinytest2_webapp_functionality <- function(test_category = "all") {

  ## validate test_category
  # test_webapp = c(
  #   "test-webapp-ui_and_server.R",  # but this one file does not use shinytest2_webapp_functionality()
  #   "test-webapp-FIPS-functionality.R",
  #   "test-webapp-FIPS-picker-functionality.R",
  #   "test-webapp-FRS-functionality.R",
  #   "test-webapp-latlon-functionality.R",
  #   "test-webapp-NAICS-functionality.R",
  #   "test-webapp-shp-gdb-zip-functionality.R",
  #   "test-webapp-shp-json-functionality.R",
  #   "test-webapp-shp-unzip-functionality.R",
  #   "test-webapp-shp-zip-functionality.R"
  # )
  # valid_categories = c(
  #   ## "ui_and_server", # not shinytest2 just regular testthat tests
  #   "FIPS", "FIPS-picker", "FRS", "latlon", "NAICS",
  #   "shp-gdb-zip", "shp-json", "shp-unzip", "shp-zip")
  testfolder = file.path(normalizePath(testthat::test_path()))
  found_categories = gsub("^test-webapp-(.*)-functionality.R", "\\1", list.files(path = testfolder, pattern = "test-.*-functionality.R"))
  valid_categories = found_categories ## NOT c(found_categories, "ui_and_server")
  if (length(valid_categories) == 0) {stop("cannot find any test files like test-webapp-xyz-functionality.R in ", testfolder)}

  if (length(test_category) == 1 && "all" %in% test_category) {
    for (i in seq_along(valid_categories)) {
      shinytest2_webapp_functionality(valid_categories[i])
    }
    return(
      shinytestLogMessage(paste0("finished test category: ", "all"))
    )
  }

  if (!all(test_category %in% valid_categories)) {
    stop("invalid test_category specified - must be one of these: ", paste0(valid_categories, collapse = ", "))
  }
  ########################################################################### #

  test_that(paste0("{shinytest2} tests of ", test_category, " category"), {
    old_width <- getOption("width") # Some functions alter this and it is noisy to see warnings that options changed
    withr::defer(options(width = old_width), testthat::teardown_env())

    testthat::skip_if_not_installed("shinytest2") # should never happen, since this gets sourced by setup.R which does library(shinytest2)

    test_log_dir <- testthat::test_path("_logs")
    dir.create(test_log_dir, recursive = TRUE, showWarnings = FALSE)

    sourcefolder <- testthat::test_path("../../")
    if (basename(normalizePath(  sourcefolder )) == "EJAM"
        # && file.exists(file.path(sourcefolder, "app.R")) # not needed since now a temp version of app.R gets created in a temp folder for this testing, to help ensure it can use isPublic=F, etc.
        ) {
      # ok
    } else {
      message("might not be finding the correct folder to use as root")
    }
    ## CREATE TEMP DIR WITH TEMP VERSION OF app.R that launches app via ejamapp() for testing purposes, using isPublic = FALSE, etc.
    make_shinytest_app_dir <- function(sourcefolder) {
      app_dir <- file.path(
        tempdir(),
        paste0("ejam-shinytest2-", test_category, "-", format(Sys.time(), "%Y%m%d%H%M%OS3"))
      )
      dir.create(app_dir, recursive = TRUE, showWarnings = FALSE)

      sourcefolder_norm <- normalizePath(sourcefolder, winslash = "/", mustWork = TRUE)
      pandoc_dir <- rmarkdown::find_pandoc()$dir
      writeLines(
        c(
          "# Autogenerated by tests/testthat/setup-shinytest2.R",
          "options(golem.app.prod = TRUE)",
          "options(shiny.testmode = TRUE)",
          if (!is.null(pandoc_dir) && nzchar(pandoc_dir)) {
            paste0("Sys.setenv(RSTUDIO_PANDOC = ", deparse(pandoc_dir), ")")
          },
          paste0(
            "sourcefolder <- normalizePath(",
            deparse(sourcefolder_norm),
            ", winslash = '/', mustWork = TRUE)"
          ),
          "pkgload::load_all(sourcefolder, quiet = TRUE, helpers = FALSE, export_all = FALSE)",
          "getExportedValue('EJAM', 'ejamapp')(",
          "  isPublic = FALSE,",
          "  default_shiny.testmode = TRUE,",
          "  default_testing = TRUE",
          ")"
        ),
        con = file.path(app_dir, "app.R")
      )
      app_dir
    }
    app_dir_for_test <- make_shinytest_app_dir(sourcefolder)
    on.exit(unlink(app_dir_for_test, recursive = TRUE, force = TRUE), add = TRUE)

    app <- shinytest2::AppDriver$new(
      app_dir = app_dir_for_test,
      variant = shinytest2::platform_variant(),
      name = test_category,
      seed=12345,
      load_timeout= 120 * 1000, # 120 * 1000 means wait up to 2 minutes  !
      width = 1920,
      screenshot_args = FALSE,
      expect_values_screenshot_args = FALSE,
      height = 1080,
      options = list(
        shiny.reactlog = TRUE,
        shiny.trace = TRUE
      )
    )
    ########################################################################### #

    # Define helper functions  ####

    ################## #
    run_full_basic_checks <- function() {
      identical(test_category, "latlon")
    }
    ################## #
    customExpectValues <- function(inputs = FALSE,
                                   outputs = NULL,
                                   exports = FALSE,
                                   name = NULL) {
      if (name %in% c("analysis1", "rad15", "counties-analysis")) {
        expect_analysis_checkpoint(name, full = run_full_basic_checks())
      } else if (name %in% c("site-by-site", "counties-site-by-site")) {
        expect_details_table_rendered()
      } else if (name %in% c("plot_avg", "demo", "environ", "EJ-ind", "EJ-Supp")) {
        expect_plot_rendered("summ_display_bar")
      } else if (name %in% c("plot_rng", "hist-sites", "hist-raw", "hist-bins20",
                             "hist-ppl", "hist-pctile", "hist-demo", "hist-raw2",
                             "hist-lowinc")) {
        expect_plot_rendered("summ_display_hist")
      } else if (!is.null(outputs)) {
        for (output_id in outputs) {
          expect_output_value_present(output_id)
        }
      } else {
        expect_analysis_checkpoint(name)
      }
    }
    ################## #
    shinytestLogMessage <- function(msg) {
      # prints the message directly to the console and to a txt file
      # in case the session crashes
      logmsg <- paste0(test_category, ": ", Sys.time(), ": ", msg, "\n")
      cat(logmsg)
      # write(logmsg,file="shinytestlog.txt",append=TRUE)
    }
    ################## #
    js_string <- function(x) {
      jsonlite::toJSON(x, auto_unbox = TRUE)
    }
    ################## #
    expect_export_true <- function(export_name) {
      exports_now <- app$get_values(export = TRUE)$export
      testthat::expect_true(export_name %in% names(exports_now))
      testthat::expect_true(isTRUE(exports_now[[export_name]]))
    }
    ################## #
    output_value_is_present <- function(value) {
      if (is.null(value) || length(value) == 0) {
        return(FALSE)
      }
      if (is.character(value)) {
        return(any(nzchar(value)))
      }
      if (is.list(value)) {
        return(length(value) > 0)
      }
      TRUE
    }
    ################## #
    expect_output_value_present <- function(output_id) {
      outputs_now <- app$get_values(output = TRUE)$output
      testthat::expect_true(output_id %in% names(outputs_now))
      testthat::expect_true(output_value_is_present(outputs_now[[output_id]]))
    }
    ################## #
    expect_input_value <- function(input_id, expected) {
      testthat::expect_equal(
        as.character(app$get_value(input = input_id)),
        as.character(expected)
      )
    }
    ################## #
    uploaded_file_names <- function(uploaded) {
      if (is.null(uploaded)) {
        return(character())
      }
      if (is.data.frame(uploaded) && "name" %in% names(uploaded)) {
        return(as.character(uploaded$name))
      }
      if (is.list(uploaded) && !is.null(uploaded$name)) {
        return(as.character(uploaded$name))
      }
      as.character(unlist(uploaded, recursive = TRUE, use.names = FALSE))
    }
    ################## #
    expect_uploaded_file <- function(input_id, expected_names) {
      app$wait_for_value(
        input = input_id,
        ignore = list(NULL),
        timeout = 20 * 1000
      )
      actual_names <- uploaded_file_names(app$get_value(input = input_id))
      testthat::expect_true(
        all(expected_names %in% actual_names),
        info = paste0(
          input_id, " uploaded files were: ",
          paste(actual_names, collapse = ", ")
        )
      )
    }
    ################## #
    expect_dom_output_present <- function(output_id) {
      app$wait_for_js(
        paste0(
          "document.getElementById(", js_string(output_id), ") !== null && ",
          "document.getElementById(", js_string(output_id), ").children.length > 0"
        ),
        timeout = 20 * 1000
      )
      expect_output_value_present(output_id)
    }
    ################## #
    expect_plot_rendered <- function(output_id) {
      app$wait_for_js(
        paste0(
          "(function(){",
          "var el = document.getElementById(", js_string(output_id), ");",
          "if (!el) return false;",
          "var img = el.querySelector('img');",
          "return !!(img && img.naturalWidth > 0 && img.naturalHeight > 0);",
          "})()"
        ),
        timeout = 20 * 1000
      )
      expect_output_value_present(output_id)
    }
    ################## #
    expect_analysis_checkpoint <- function(name = NULL, full = FALSE) {
      expect_export_true("analysis_complete")
      if (!isTRUE(full)) {
        return(invisible(TRUE))
      }

      wait_for_results_ready(result = "multisite_report_download_ready")
      expect_export_true("multisite_report_download_ready")
      expect_dom_output_present("comm_report_html")
      expect_plot_rendered("report_plot_output")
      if (!(test_category %in% c("shp-zip", "shp-gdb-zip", "shp-json", "shp-unzip"))) {
        expect_dom_output_present("quick_view_map")
      }
      invisible(TRUE)
    }
    ################## #
    expect_details_table_rendered <- function() {
      app$wait_for_js(
        "(function(){
          var el = document.getElementById('interactive_table');
          return !!(el && (el.querySelector('table') || el.querySelector('.dataTables_wrapper')));
        })()",
        timeout = 20 * 1000
      )
      expect_output_value_present("interactive_table")
    }
    ################## #
    custom_binary_xlsx_download <- function(outputId, name = test_category) {
      if (!rmarkdown::pandoc_available()) {
        shinytestLogMessage("Skipping results spreadsheet download assertion because pandoc is not available")
        return(invisible(NA_character_))
      }

      download_filepath <- tryCatch(
        app$get_download(outputId),
        error = function(cond) {
          shinytestLogMessage(conditionMessage(cond))
          stop(cond)
        })

      testthat::expect_true(file.exists(download_filepath))
      downloaded_ext <- tolower(tools::file_ext(download_filepath))
      if (nzchar(downloaded_ext)) {
        testthat::expect_equal(downloaded_ext, "xlsx")
      }
      testthat::expect_identical(
        readBin(download_filepath, what = "raw", n = 2),
        charToRaw("PK")
      )
      testthat::expect_gt(file.info(download_filepath)$size, 50 * 1024)

      sheet_names <- readxl::excel_sheets(download_filepath)
      required_sheets <- c("Each Site", "Overall", "notes")
      testthat::expect_true(all(required_sheets %in% sheet_names))
      testthat::expect_gte(length(sheet_names), length(required_sheets))

      for (sheet in c("Each Site", "Overall")) {
        sheet_data <- readxl::read_xlsx(download_filepath, sheet = sheet, col_names = FALSE)
        testthat::expect_gt(NROW(sheet_data), 1)
        testthat::expect_gt(NCOL(sheet_data), 5)
      }

      notes_data <- readxl::read_xlsx(download_filepath, sheet = "notes", col_names = FALSE)
      testthat::expect_gt(NROW(notes_data), 0)
      invisible(download_filepath)
    }
    ################## #
    save_log <- function(fname) {
      fname <- file.path(test_log_dir, basename(fname))
      logs <- app$get_logs()
      capture.output(
        logs[logs$location != "chromote" & nchar(logs$message) < 1000, ],
        file = fname
      )
    }
    ################## #
    selectize_set_values <- function(input_id, values, labels = values) {
      values <- as.character(values)
      labels <- as.character(labels)
      app$run_js(sprintf(
        "
          var el = document.getElementById(%s);
          var values = %s;
          var labels = %s;
          if (el && el.selectize) {
            values.forEach(function(value, i) {
              el.selectize.addOption({
                value: value,
                text: labels[i] || value
              });
            });
            el.selectize.setValue(values);
            el.selectize.refreshOptions(false);
          }
        ",
        jsonlite::toJSON(input_id, auto_unbox = TRUE),
        jsonlite::toJSON(values, auto_unbox = FALSE),
        jsonlite::toJSON(labels, auto_unbox = FALSE)
      ))
    }
    ################## #
    picker_values_are_selected <- function(input_id, values) {
      picked <- app$get_value(input = input_id)
      setequal(as.character(picked), as.character(values))
    }
    ################## #
    expect_category_selection <- function() {
      if (test_category == "latlon") {
        expect_input_value("ss_choose_method", "upload")
        expect_uploaded_file("ss_upload_latlon", "testpoints_10.xlsx")
      } else if (test_category == "FIPS") {
        expect_input_value("ss_choose_method", "upload")
        expect_input_value("ss_choose_method_upload", "FIPS")
        expect_uploaded_file("ss_upload_fips", "counties_in_Delaware.xlsx")
      } else if (test_category == "shp-zip") {
        expect_input_value("ss_choose_method", "upload")
        expect_input_value("ss_choose_method_upload", "SHP")
        expect_uploaded_file("ss_upload_shp", "portland_shp.zip")
      } else if (test_category == "shp-gdb-zip") {
        expect_input_value("ss_choose_method", "upload")
        expect_input_value("ss_choose_method_upload", "SHP")
        expect_uploaded_file("ss_upload_shp", "portland.gdb.zip")
      } else if (test_category == "shp-json") {
        expect_input_value("ss_choose_method", "upload")
        expect_input_value("ss_choose_method_upload", "SHP")
        expect_uploaded_file("ss_upload_shp", "portland.json")
      } else if (test_category == "shp-unzip") {
        expect_input_value("ss_choose_method", "upload")
        expect_input_value("ss_choose_method_upload", "SHP")
        expect_uploaded_file(
          "ss_upload_shp",
          c(
            "Neighborhoods_regions.dbf",
            "Neighborhoods_regions.prj",
            "Neighborhoods_regions.shp",
            "Neighborhoods_regions.shx"
          )
        )
      } else if (test_category == "FRS") {
        expect_input_value("ss_choose_method", "upload")
        expect_input_value("ss_choose_method_upload", "FRS")
        expect_uploaded_file("ss_upload_frs", "frs_testpoints_10.xlsx")
      } else if (test_category == "NAICS") {
        expect_input_value("ss_choose_method", "dropdown")
        expect_input_value("ss_choose_method_drop", "NAICS")
        expect_input_value("ss_select_naics", "114")
      } else if (test_category == "FIPS-picker") {
        expect_input_value("ss_choose_method", "dropdown")
        expect_input_value("ss_choose_method_drop", "FIPS_PLACE")
        expect_input_value("pickermoduleid-fips_type2pick", "Cities or Places")
        testthat::expect_true(
          picker_values_are_selected("pickermoduleid-cities_picked", "3684000")
        )
      }

      invisible(TRUE)
    }
    ################## #
    select_fips_picker_values <- function(area_type, input_id, values, labels = values, label_for_log = area_type) {
      values <- as.character(values)

      shinytestLogMessage("select dropdown Categories method of site selection")
      app$set_inputs(ss_choose_method = "dropdown", wait_ = FALSE)
      app$set_inputs(ss_choose_method_drop = "FIPS_PLACE", wait_ = FALSE)
      app$wait_for_idle(timeout = 10 * 1000)

      shinytestLogMessage(paste0("select ", area_type, " as method of site selection"))
      app$set_inputs(`pickermoduleid-fips_type2pick` = area_type)
      app$wait_for_idle(timeout = 10 * 1000)

      shinytestLogMessage(paste0("specify ", label_for_log))
      for (attempt in 1:3) {
        args <- c(setNames(list(values), input_id), list(wait_ = FALSE))
        do.call(app$set_inputs, args)
        app$wait_for_idle(timeout = 10 * 1000)
        picked <- app$get_value(input = input_id)
        shinytestLogMessage(paste0(
          input_id, " after selection attempt ", attempt, ": ",
          paste(picked, collapse = ",")
        ))
        if (picker_values_are_selected(input_id, values)) {
          break
        }
      }

      if (!picker_values_are_selected(input_id, values)) {
        shinytestLogMessage(paste0(input_id, " not fully selected, using selectize js fallback"))
        selectize_set_values(input_id = input_id, values = values, labels = labels)
        app$wait_for_idle(timeout = 10 * 1000)
        picked <- app$get_value(input = input_id)
        shinytestLogMessage(paste0(
          input_id, " after js fallback: ",
          paste(picked, collapse = ",")
        ))
      }

      testthat::expect_true(
        picker_values_are_selected(input_id, values)
      )

      shinytestLogMessage("click done")
      tryCatch(
        {
          app$click("fipspicker_done_button", wait_ = FALSE)
          app$wait_for_idle(timeout = 10 * 1000)
          app$wait_for_js(
            "document.getElementById('bt_get_results') !== null && !document.getElementById('bt_get_results').disabled",
            timeout = 20 * 1000
          )
        },
        error = function(e) {
          save_log(paste0(test_category, "-post-done-log.txt"))
          stop(e)
        }
      )
    }
    ################## #
    custom_html_report_download <- function(outputId) {
      if (!rmarkdown::pandoc_available()) {
        shinytestLogMessage("Skipping community report download assertion because pandoc is not available")
        return(invisible(NA_character_))
      }

      download_filepath <- tryCatch(
        app$get_download(outputId),
        error = function(cond) {
          save_log("EJAM_app_test_report_download_log.txt")
          shinytestLogMessage(conditionMessage(cond))
          stop(cond)
        }
      )

      testthat::expect_true(
        file.exists(download_filepath)
      )
      downloaded_ext <- tolower(tools::file_ext(download_filepath))
      if (nzchar(downloaded_ext)) {
        testthat::expect_true(downloaded_ext %in% c("html", "htm"))
      }
      testthat::expect_gt(
        file.info(download_filepath)$size,
        50 * 1024
      )

      html <- readLines(download_filepath, warn = FALSE, encoding = "UTF-8")
      html_text <- paste(html, collapse = "\n")
      stable_text <- c(
        "<html",
        "data-indicators-table",
        "Population",
        "Particulate Matter"
      )
      for (txt in stable_text) {
        testthat::expect_true(
          grepl(txt, html_text, fixed = TRUE)
        )
      }

      invisible(download_filepath)
    }
    ################## #
    wait_for_results_ready <- function(
      result = "analysis_complete",
      timeout = if (test_category == "FIPS-picker") 5 * 60 * 1000 else 2 * 60 * 1000
    ) {
      tryCatch(
        app$wait_for_value(
          export = result,
          ignore = list(FALSE, NULL),
          timeout = timeout
        ),
        error = function(e) {
          save_log(paste0(test_category, "-", result, "-timeout-log.txt"))
          vals <- try(app$get_values(export = TRUE), silent = TRUE)
          if (!inherits(vals, "try-error")) {
            cat("Exports visible at timeout:\n")
            print(names(vals$export))
            print(vals$export)
          }
          stop(e)
        }
      )
    }
    ################## #
    wait_for_start_analysis_enabled <- function(timeout = 60 * 1000) {
      app$wait_for_js(
        "document.getElementById('bt_get_results') !== null && !document.getElementById('bt_get_results').disabled",
        timeout = timeout
      )
    }
    ########################################################################### #
    # ~ ------------------------------------------------ ####
    # SCREEN RECORDING / SCRIPT: ####
    # ~ ------------------------------------------------ ####

    # 1) SPECIFY SITES ####

    ## by UPLOADED FILE of given type ####

    app$set_inputs(ss_choose_method = "upload", wait_ = FALSE)
    if(test_category == "latlon") {
      ### > latlon ####
      shinytestLogMessage("About to upload latlon testpoints_10.xlsx")
      app$upload_file(ss_upload_latlon = EJAM:::app_sys("testdata/latlon/testpoints_10.xlsx"))
    } else if(test_category == "FIPS") {
      ### > FIPS ####
      shinytestLogMessage("About to upload counties_in_Delaware.xlsx for FIPS")
      app$set_inputs(ss_choose_method_upload = "FIPS", wait_ = FALSE)
      app$upload_file(ss_upload_fips = EJAM:::app_sys("testdata/fips/counties_in_Delaware.xlsx"))
    } else if(test_category == "shp-zip") {
      ### > shp-zip ####
      shinytestLogMessage("About to upload portland_shp.zip for SHP")
      app$set_inputs(ss_choose_method_upload = "SHP", wait_ = FALSE)
      app$upload_file(ss_upload_shp = EJAM:::app_sys("testdata/shapes/portland_shp.zip"))
    } else if(test_category == "shp-gdb-zip") {
      ### > shp-gdb-zip ####
      shinytestLogMessage("About to upload portland.gdp.zip for SHP")
      app$set_inputs(ss_choose_method_upload = "SHP", wait_ = FALSE)
      app$upload_file(ss_upload_shp = EJAM:::app_sys("testdata/shapes/portland.gdb.zip"))
    } else if(test_category == "shp-json") {
      ### > shp-json ####
      shinytestLogMessage("About to upload portland.json for SHP")
      app$set_inputs(ss_choose_method_upload = "SHP", wait_ = FALSE)
      app$upload_file(ss_upload_shp = EJAM:::app_sys("testdata/shapes/portland.json"))
    } else if(test_category == "shp-unzip") {
      ### > shp-unzip ####
      shinytestLogMessage("About to upload individual shapefiles for SHP")
      app$set_inputs(ss_choose_method_upload = "SHP", wait_ = FALSE)
      app$upload_file(ss_upload_shp = c(EJAM:::app_sys("testdata/shapes/portland_folder_shp/Neighborhoods_regions.dbf"),
                                        EJAM:::app_sys("testdata/shapes/portland_folder_shp/Neighborhoods_regions.prj"),
                                        EJAM:::app_sys("testdata/shapes/portland_folder_shp/Neighborhoods_regions.shp"),
                                        EJAM:::app_sys("testdata/shapes/portland_folder_shp/Neighborhoods_regions.shx")))
    } else if(test_category == "FRS") {
      ### > FRS ####
      shinytestLogMessage("About to upload frs_testpoints_10.xlsx for FRS")
      app$set_inputs(ss_choose_method_upload = "FRS", wait_ = FALSE)
      app$upload_file(ss_upload_frs = EJAM:::app_sys("testdata/registryid/frs_testpoints_10.xlsx"))
    }

    ## by CATEGORY IN DROPDOWN MENU ####

    if (test_category == "NAICS") {
      ### > NAICS ####
      shinytestLogMessage("selecting 114 for NAICS")
      app$set_inputs(ss_choose_method = "dropdown", wait_ = FALSE)
      app$set_inputs(ss_choose_method_drop = "NAICS", wait_ = FALSE) # this is default
      # cannot do 1111 - no longer exists with new UI - would need to switch to Detailed list
      # cannot do 111 - too large for shiny. Gets a memory issue and crashes
      app$set_inputs(ss_select_naics = "114", wait_ = FALSE) #, timeout_ = 10000)
    }
    ########################################################################### #

    if (test_category == "FIPS-picker") {
      select_fips_picker_values(
        area_type = "Cities or Places",
        input_id = "pickermoduleid-cities_picked",
        values = "3684000",
        labels = "Yonkers city, Westchester County, NY (3684000)",
        label_for_log = "one city"
      )
    }
    ########################################################################### #

    expect_category_selection()

    ########################################################################### #
    #  TESTS FOR FIPS PICKER
    ########################################################################### #

    if (FALSE && test_category %in% "FIPS-picker") {
      ### > City (but County/State not tested here)    ####

      shinytestLogMessage("will test selecting 1 city from dropdown")

      app$set_inputs(`shinyjs-resettable-ss_upload_latlon` = character(0), allow_no_input_binding_ = TRUE)
      app$set_inputs(`shinyjs-resettable-ss_upload_shp` = character(0), allow_no_input_binding_ = TRUE)
      app$set_inputs(`shinyjs-resettable-ss_upload_frs` = character(0), allow_no_input_binding_ = TRUE)
      app$set_inputs(`shinyjs-resettable-ss_upload_program` = character(0), allow_no_input_binding_ = TRUE)
      app$set_inputs(`shinyjs-resettable-ss_upload_fips` = character(0), allow_no_input_binding_ = TRUE)
      ################################################ #
      shinytestLogMessage("using initial map")
      app$set_window_size(width = 1339, height = 994)
      app$set_inputs(an_leaf_map_bounds = c(54.6229781326903, -61.611328125, 21.0434912168035, -135.439453125), allow_no_input_binding_ = TRUE)
      app$set_inputs(an_leaf_map_center = c(-98.525390625, 39.8422860207434), allow_no_input_binding_ = TRUE)
      app$set_window_size(width = 1339, height = 994)

      app$set_inputs(default_naics = "313")
      app$set_inputs(ss_select_naics = "313")
      app$set_inputs(default_sic = "2015")
      app$set_inputs(ss_select_sic = "2015")
      app$set_inputs(an_leaf_map_bounds = c(54.6229781326903, -58.88671875, 21.0434912168035, -138.251953125), allow_no_input_binding_ = TRUE)
      app$set_inputs(an_leaf_map_center = c(-98.5693359375, 39.8422860207434), allow_no_input_binding_ = TRUE)
      app$set_window_size(width = 1434, height = 1158)
      app$set_inputs(an_leaf_map_bounds = c(54.6229781326903, -45.703125, 21.0434912168035, -151.435546875), allow_no_input_binding_ = TRUE)
      app$set_window_size(width = 1883, height = 1158)
      ################################################ #

      shinytestLogMessage("select dropdown Categories method of site selection")
      app$set_inputs(ss_choose_method = "dropdown")

      app$set_inputs(an_leaf_map_bounds = c(54.6229781326903, -56.865234375, 21.0434912168035, -140.2734375), allow_no_input_binding_ = TRUE)
      app$set_window_size(width = 1502, height = 1158)
      ################################################ #

      shinytestLogMessage("select 'Cities of Places' as method of site selection")
      app$set_inputs(`pickermoduleid-fips_type2pick` = "Cities or Places")

      app$set_inputs(`pickermoduleid-states_picked` = c("AL", "AK", "AZ", "AR", "CA",
                                                        "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY",
                                                        "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
                                                        "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX",
                                                        "UT", "VT", "VA", "WA", "WV", "WI", "WY", "AS", "GU", "MP", "PR", "UM", "VI"))
      ################################################ #

      shinytestLogMessage("specify one city")
      app$set_inputs(`pickermoduleid-cities_picked` = "3684000")
      ################################################ #
      shinytestLogMessage("click done")
      app$click("fipspicker_done_button")

      # is there a way to wait until map is ready here?

      ################################################ #
      shinytestLogMessage("mouseover preview map")
      app$set_inputs(an_leaf_map_shape_mouseover = c(0.421320887360868, 40.9573205538086,
                                                     -73.8291341303544), allow_no_input_binding_ = TRUE)
      shinytestLogMessage("click shape on map")
      app$set_inputs(an_leaf_map_shape_click = c(0.42315841908534, 40.9433181283034,
                                                 -73.8686302283186), allow_no_input_binding_ = TRUE)
      ################################################ #
      shinytestLogMessage("expect preview map")

      # is there a way to wait until map is ready here?

      expect_dom_output_present("an_leaf_map")
      ################################################ #
      shinytestLogMessage("mousing")
      app$set_inputs(an_leaf_map_shape_mouseout = c(0.488682803768655, 40.9433181283034,
                                                    -73.8686302283186), allow_no_input_binding_ = TRUE)
      app$set_inputs(an_leaf_map_shape_mouseover = c(0.353217325016352, 40.940724760675,
                                                     -73.8724081159499), allow_no_input_binding_ = TRUE)
      app$set_inputs(an_leaf_map_shape_mouseout = c(0.0315728309706905, 40.8953243445332,
                                                    -73.8597006757354), allow_no_input_binding_ = TRUE)
      ################################################ #

      shinytestLogMessage("GET RESULTS")
      # Update this to work like the other shinytest2 tests that worked
      app$click("bt_get_results")
      ################################################ #

      shinytestLogMessage("EXPECT REPORT HTML")

      # Update this to work like the other shinytest2 tests that worked
      # use a way to wait until map is ready here
      # like wait_for_results_ready() ***

      expect_dom_output_present("comm_report_html")
      ################################################ #
      shinytestLogMessage("mousing on report's results map")
      app$set_inputs(quick_view_map_shape_mouseover = c(0.424042970362076, 40.9116051954735,
                                                        -73.8545608520508), allow_no_input_binding_ = TRUE)

      shinytestLogMessage("click on report's results map")
      app$set_inputs(quick_view_map_shape_click = c(0.574973725370002, 40.9362489359378,
                                                    -73.8607406616211), allow_no_input_binding_ = TRUE)
      ################################################ #

      shinytestLogMessage("EXPECT REPORT OF RESULTS TO SHOW MAP")

      # is there a way to wait until map is ready here?

      expect_dom_output_present("quick_view_map")
      ################################################ #
      app$set_inputs(quick_view_map_shape_mouseout = c(0.0900601374075561, 40.9362489359378,
                                                       -73.8607406616211), allow_no_input_binding_ = TRUE)
      app$set_inputs(quick_view_map_bounds = c(41.0001116336573, -73.6200714111328, 40.8963867461564,
                                               -74.1086196899414), allow_no_input_binding_ = TRUE)
      app$set_inputs(quick_view_map_center = c(-73.8643455505371, 40.9482695567752),
                     allow_no_input_binding_ = TRUE)
      app$set_inputs(quick_view_map_shape_mouseover = c(0.0165197251473244, 40.9328771773305,
                                                        -73.8624572753906), allow_no_input_binding_ = TRUE)
      app$set_inputs(quick_view_map_shape_mouseout = c(0.495737726676899, 40.9349521260697,
                                                       -73.8662338256836), allow_no_input_binding_ = TRUE)
      app$set_inputs(quick_view_map_shape_mouseover = c(0.548687330576262, 40.9383237787759,
                                                        -73.8964462280274), allow_no_input_binding_ = TRUE)
      app$set_inputs(quick_view_map_shape_mouseout = c(0.287342401223261, 40.9001881389278,
                                                       -73.9033126831055), allow_no_input_binding_ = TRUE)

      ################################################ #
      shinytestLogMessage("DETAILS TAB")

      app$set_inputs(results_tabs = "Details")

      shinytestLogMessage("DETAILED INTERACTIVE TABLE")

      # is there a way to wait until TABLE is ready here?

      app$set_inputs(interactive_table_rows_current = 1, allow_no_input_binding_ = TRUE)
      app$set_inputs(interactive_table_rows_all = 1, allow_no_input_binding_ = TRUE)

      app$set_inputs(interactive_table_state = c(1776974771683, 0, 100, "", TRUE, FALSE,
                                                 TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE,
                                                                                                                         "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE,
                                                                                                                                                                                   FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                                                                                   TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE),
                                                 c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "",
                                                                                                                   TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE,
                                                                                                                                                                         TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)),
                     allow_no_input_binding_ = TRUE)

      ################################################ #
      shinytestLogMessage("CLICK CELL IN INTERACTIVE TABLE")
      app$set_inputs(interactive_table_cell_clicked = c("1", "4", ""), allow_no_input_binding_ = TRUE, priority_ = "event")

      ################################################ #
      shinytestLogMessage("CLICK URL LINK IN INTERACTIVE TABLE")
      app$set_inputs(interactive_table_cell_clicked = c("1", "1", "<a href=\"https://ejamapi-84652557241.us-central1.run.app/report?fips=3684000&buffer=0&sitetype=fips&validate_regids=FALSE\" target=\"_blank\">EJAM Site Report</a>"),
                     allow_no_input_binding_ = TRUE, priority_ = "event")

      ################################################ #
      shinytestLogMessage("EXPECT VALUE / INTERACTIVE TABLE")

      # is this the correct way to check for the table?

      expect_details_table_rendered()



      ## done with FIPS-picker case


















    }
    ########################################################################### #
    ########################################################################### #
    ########################################################################### #
    if (test_category == "EPA") {
      ### > EPA program  not tested here  ####

      # placeholder

    }

    if (test_category == "SIC") {
      ### > SIC  not tested here  ####

      # placeholder

    }

    if (test_category == "MACT") {
      ### > MACT  not tested here  ####

      # placeholder

    }

    ########################################################################### #
    # ~ ------------------------------------------------ ####

    # 2) START ANALYSIS ####

    shinytestLogMessage("Click to run analysis"); print("Click to run analysis")
    wait_for_start_analysis_enabled()
    app$click("bt_get_results", wait_ = FALSE)
    wait_for_results_ready(result = "analysis_complete")
    customExpectValues(name="analysis1")

    if (run_full_basic_checks()) {
      shinytestLogMessage("change map bounds and center")
      app$set_inputs(
        quick_view_map_bounds = list(
          north = 48.86471476180279,
          east = -49.17480468750001,
          south = 35.9602229692967,
          west = -130.7373046875
        ),
        allow_no_input_binding_ = TRUE
      )
      app$set_inputs(
        quick_view_map_center = list(
          lng = -89.9560546875,
          lat = 42.74701217318067
        ),
        allow_no_input_binding_ = TRUE
      )
    }

    # CHANGE radius/title, RE-RUN ANALYSIS ####

    if (run_full_basic_checks()) {
      shinytestLogMessage("go back to Site Selection tab")
      app$set_inputs(all_tabs = "Site Selection", wait_ = FALSE)
      app$wait_for_idle(timeout = 5 * 1000)

      shinytestLogMessage("change radius (to 1.5)")
      app$set_inputs(radius_now = 1.5, wait_=FALSE)

      shinytestLogMessage("change analysis title (to 'Summary of Analysis2')")
      app$set_inputs(analysis_title = "Summary of Analysis2")

      shinytestLogMessage("Click to run analysis again")
      wait_for_start_analysis_enabled()
      app$click("bt_get_results", wait_ = FALSE)
      wait_for_results_ready(result = "analysis_complete")
      expect_input_value("radius_now", "1.5")
      expect_input_value("analysis_title", "Summary of Analysis2")
      customExpectValues(name="rad15")
    }
    ########################################################################### #
    # ~ ------------------------------------------------ ####

    # 3) SEE RESULTS ####
    # ~  ####

    ## SUMMARY REPORT (html DOWNLOAD) ####

    if (run_full_basic_checks()) {
      shinytestLogMessage("about to download community report")
      wait_for_results_ready(result = "multisite_report_download_ready")

      ## This step was originally getting the underlying dataframe
      ## output_df, from the report download function in app_server.R
      ## because the actual downloaded report was large
      ## so the downloaded file was saved to the tempdir()
      ## and within that function, we called exportTestvalues() to save output_df
      ##
      ##   maybe there is a better way to download the html report? ***
      #
      # app$get_download("download_report_multisite")
      # customExpectValues(name="comm", inputs=FALSE, outputs=FALSE, exports=c("download_report_multisite")) # this should grab just the underlying df behind the export

      custom_html_report_download("download_report_multisite")
    }
    ########################################################################### #
    # ~  ####

    ## DETAILS tab ####

    if (run_full_basic_checks()) {
      shinytestLogMessage("going to details tab")
      app$set_inputs(results_tabs = "Details")
      app$wait_for_idle(timeout = 5 * 1000)
      shinytestLogMessage("should see the results table from details tab")
      ## or could wait until available, with a timeout cap, as for html webview of summary report ***
      customExpectValues(name="site-by-site")
    }

    ### > SITE by SITE (xlsx DOWNLOAD) ####

    if (run_full_basic_checks()) {
      shinytestLogMessage("downloading results table from details tab")

      ## this downloads the xlsx report, based on the download_results_spreadsheet output in app_server.R
      ## since shinytest2 can't compare binary files, this custom download creates a hashed version
      ## and saves the hash to be compared in future test runs

      # app$wait_for_idle(timeout = 60 * 1000)
      # app$expect_download("download_results_spreadsheet") # use custom... func instead:
      ## download xlsx file using the helper function
      custom_binary_xlsx_download("download_results_spreadsheet")
    }

    # save_log("EJAM_app_test_log_pre_results_download.txt")
    ########################################################################### #

    if (test_category == "FIPS-picker") {
      shinytestLogMessage("go back to Site Selection tab to test county picker")
      app$set_inputs(all_tabs = "Site Selection", wait_ = FALSE)
      app$wait_for_idle(timeout = 5 * 1000)

      select_fips_picker_values(
        area_type = "Counties",
        input_id = "pickermoduleid-counties_picked",
        values = c("10001", "10003", "10005"),
        labels = c("Kent County, DE", "New Castle County, DE", "Sussex County, DE"),
        label_for_log = "three Delaware counties"
      )

      shinytestLogMessage("Click to run analysis for three Delaware counties")
      wait_for_start_analysis_enabled(timeout = 20 * 1000)
      app$click("bt_get_results", wait_ = FALSE)
      wait_for_results_ready(result = "analysis_complete")
      expect_input_value("pickermoduleid-fips_type2pick", "Counties")
      testthat::expect_true(
        picker_values_are_selected("pickermoduleid-counties_picked", c("10001", "10003", "10005"))
      )
      customExpectValues(name = "counties-analysis")
    }

    ########################################################################### #

    ### > PLOT AVERAGE SCORES (BARPLOTS) ####

    ## only test plots for latlon case - should be same as for other cases

    if (test_category %in% c("latlon")) {
      shinytestLogMessage("going to plot_average details subtab")
      app$set_inputs(details_subtabs = "Plot Average Scores")
      app$wait_for_idle(timeout = 5 * 1000)
      customExpectValues(name="plot_avg")

      shinytestLogMessage("Demographic summ_bar-ind")
      app$set_inputs(summ_bar_ind = "Demographic")
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_bar_ind", "Demographic")
      customExpectValues(name="demo")

      shinytestLogMessage("Environmental summ_bar_ind")
      app$set_inputs(summ_bar_ind = "Environmental")
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_bar_ind", "Environmental")
      customExpectValues(name="environ")

      if(app$get_value(input="include_ejindexes") == "TRUE") {
        shinytestLogMessage("EJ summ_bar-ind")
        app$set_inputs(summ_bar_ind = "EJ Index", wait_ = FALSE)
        app$wait_for_idle(timeout = 5 * 1000)
        expect_input_value("summ_bar_ind", "EJ Index")
        customExpectValues(name="EJ-ind")

        shinytestLogMessage("EJ supplemental")
        app$set_inputs(summ_bar_ind = "Supplementary EJ Index", wait_ = FALSE)
        app$wait_for_idle(timeout = 5 * 1000)
        expect_input_value("summ_bar_ind", "Supplementary EJ Index")
        customExpectValues(name="EJ-Supp")
      }

      ### > PLOT FULL RANGE OF SCORES (HISTOGRAM) ####

      shinytestLogMessage("going to plot_range details subtab")
      app$set_inputs(details_subtabs = "Plot Full Range of Scores")
      app$wait_for_idle(timeout = 5 * 1000)
      customExpectValues(name="plot_rng")

      shinytestLogMessage("histogram of Sites")
      app$set_inputs(summ_hist_distn = "Sites")
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_distn", "Sites")
      customExpectValues(name="hist-sites")

      shinytestLogMessage("histogram of raw data")
      app$set_inputs(summ_hist_data = "raw")
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_data", "raw")
      customExpectValues(name="hist-raw")

      shinytestLogMessage("histogram with 15 bins, 20 bins")
      app$set_inputs(summ_hist_bins = 15)
      app$wait_for_idle(timeout = 5 * 1000)
      app$set_inputs(summ_hist_bins = 20)
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_bins", "20")
      customExpectValues(name="hist-bins20")

      shinytestLogMessage("histogram of People")
      app$set_inputs(summ_hist_distn = "People")
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_distn", "People")
      customExpectValues(name="hist-ppl")

      shinytestLogMessage("histogram of percentiles across people")
      app$set_inputs(summ_hist_data = "pctile")
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_data", "pctile")
      customExpectValues(name="hist-pctile")

      shinytestLogMessage("histogram of pctile Demog Index Supp")
      app$set_inputs(summ_hist_ind = "Demog.Index.Supp", allow_no_input_binding_ = TRUE)
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_ind", "Demog.Index.Supp")
      customExpectValues(name="hist-demo")

      shinytestLogMessage("histogram of raw scores across people")
      app$set_inputs(summ_hist_data = "raw")
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_data", "raw")
      customExpectValues(name="hist-raw2")

      shinytestLogMessage("histogram of percent low income")
      app$set_inputs(summ_hist_ind = "pctlowinc", allow_no_input_binding_ = TRUE)
      app$wait_for_idle(timeout = 5 * 1000)
      expect_input_value("summ_hist_ind", "pctlowinc")
      customExpectValues(name="hist-lowinc")
    }
    ########################################################################### #
    ########################################################################### #

    ########################################################################### #

    shinytestLogMessage(paste0("finished test category: ", test_category))
  })
}
########################################################################### #

## This used to Load all .R / application support files into testing environment, but
## should not be needed since
##  library(EJAM) loads all needed functions - but note that means the package must be installed for this testing to work
## and app.R will use ejamapp() which will read all the needed global defaults

#  shinytest2::load_app_env()
