#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_formulas_ejscreen_demog_index.R or similar files

#' @name formulas_ejscreen_demog_index
#' @docType data
#' @title formulas_ejscreen_demog_index (DATA) special formulas for annually recalculating the Demog.Index annual update
#' @seealso [formulas_ejscreen_acs] [formulas_ejscreen_acs_disability]
'formulas_ejscreen_demog_index'
