# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see
# EJAM/data-raw/datacreate_runtime_models.R

#' Legacy regression model for doaggregate runtime
#'
#' @name modelDoaggregate
#' @docType data
#' @title Legacy regression model for doaggregate runtime
#' @description Regression model retained for compatibility and refit only when the current timing files contain enough doaggregate rows.
#' @details When at least five usable doaggregate timing rows are available in Analysis_timing_results*.csv files, the data-creation script models runtime from nrows_blocks with weighted least squares and up-weights small input counts when input_number is available. Otherwise it preserves the existing packaged model rather than replacing it with an unsupported sparse fit.
"modelDoaggregate"
