#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_statestats.R or similar files

#' @name statestats
#' @docType data
#' @title statestats (DATA) data.frame of 100 percentiles and means for each US State and PR and DC.
#' @description data.frame of 100 percentiles and means
#'   for each US State and PR and DC
#'   for all the blockgroups in that zone (e.g., blockgroups in [blockgroupstats])
#'   for a set of indicators such as percent low income.
#'   Each column is one indicator (or specifies the percentile).
#'
#'   For details on how the table was made, see source package files in data-raw folder.
#'
#'   See also [usastats] for more details.
'statestats'
