#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_formulas_ejscreen_acs_disability.R or similar files

#' @name formulas_ejscreen_acs_disability
#' @docType data
#' @title formulas_ejscreen_acs_disability dataset
#' @description formulas for calculating count and percent with disability, from ACS raw data
#' @details Used for annual update of ACS-based indicators related to population with disabilities. See [calc_blockgroupstats_from_tract()] and [calc_blockgroupstats_acs()]
'formulas_ejscreen_acs_disability'
