#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_naicstable.R or similar files

#' @name naicstable
#' @docType data
#' @title naicstable (DATA) data.table of all possible NAICS code(s) and industry names
#' @details data.table of all possible NAICS code(s) and industry names
#' (which get used to classify EPA-regulated sites in Facility Registry Service (FRS))
#' Also has the 2,3,4,5,and 6-digit NAICS (categories and subcategories)
#' that this code falls under, where relevant for given length.
#' Code universe was updated in 2022, but EPA FRS as of 2025
#' was still using NAICS codes from the 2017 update of industry codes and names.
#'
#' This is similar to the data file EJAM::NAICS but in a more useful format and newer functions work with it.
#' see [NAICS.com](https://naics.com)
#' @seealso [EJAM::naics_from_any()] [EJAM::NAICS]  [EJAM::naics_categories()]  [EJAM::naics_findwebscrape()]
'naicstable'
