#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_formulas_ejscreen_acs.R or similar files

#' @name formulas_ejscreen_acs
#' @docType data
#' @title formulas_ejscreen_acs dataset
#' @description Formulas and metadata about Census ACS variables and how to calculate indicators from those raw Census variables, such as creating pctunder5 starting from ACS table B01001 variables.
#' @seealso `acs_bybg()`
'formulas_ejscreen_acs'
