#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_names_of_indicators.R or similar files

#' @name ejscreen_arcgis_service_field
#' @docType data
#' @title EJSCREEN ArcGIS service field names
#' @details A character vector of ArcGIS service geometry field names used in
#'   EJSCREEN exports.
#' @keywords internal
'ejscreen_arcgis_service_field'
