# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see
# EJAM/data-raw/datacreate_runtime_models.R

#' Legacy regression model for point-buffer ejamit analyses
#'
#' @name modelEjamit
#' @docType data
#' @title Legacy regression model for point-buffer ejamit analyses
#' @description Weighted regression retained for compatibility and fallback runtime profiles.
#' @details The packaged model was trained from historical point-buffer timing rows and is preserved until the current benchmark files have enough count and radius coverage to replace it safely. Current v3.2022.2 point estimates use measured monotone runtime profiles in utils_speedtest.R because this legacy model has no training rows below 243 sites.
"modelEjamit"
