# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see
# EJAM/data-raw/datacreate_runtime_models.R

#' Regression model to predict runtime for doaggregate
#'
#' @name modelDoaggregate
#' @docType data
#' @title Regression model to predict runtime for doaggregate
#' @description Weighted runtime model for doaggregate, fit from Analysis_timing_results*.csv files with extra emphasis on small point-count runs.
#' @details The model is trained from all Analysis_timing_results*.csv files in data-raw/. Small runs such as 1, 2, and 10 points are up-weighted so predictions are more accurate for small analyses. doaggregate runtime is modeled from nrows_blocks using weighted least squares.
"modelDoaggregate"
