#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_names_of_indicators.R or similar files

#' @name ejscreen_schema_extra
#' @docType data
#' @title EJSCREEN schema-only extra field names
#' @details A character vector of EJSCREEN export field names that are schema
#'   extras rather than standard EJAM indicator rnames.
#' @keywords internal
'ejscreen_schema_extra'
