#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_formulas_d.R or similar files

#' @name formulas_d
#' @docType data
#' @title formulas_d (DATA) table of formulas to aggregate or calculate indicators
#' @description These formulas can describe how each indicator is calculated from
#'   raw data or intermediate variables, like population counts from Census ACS
#'   (or potentially formulas for how it is aggregated as a weighted mean, etc.)
#' @details Created for EJAM by datacreate_formulas.R script
#'
#' See also [formulas_all] and [formulas_ejscreen_acs]
#'
#' Can be used by [calc_ejam()] or [acs_bybg()] for
#'
#' 1) aggregation over blockgroups at a site or
#'
#' 2) to create a derived custom indicator for all US blockgroups
#'    based on counts obtained from the ACS.)
'formulas_d'
