#

# DO NOT EDIT THIS FILE - This dataset is maintained from current formula helpers.
# The old data-raw/archived_datacreate_formulas_ejscreen_acs_notes.R file is legacy reference only.

#' @name formulas_ejscreen_acs
#' @docType data
#' @title formulas_ejscreen_acs dataset
#' @description Formulas and metadata about Census ACS variables and how to calculate indicators from those raw Census variables, such as creating pctunder5 starting from ACS table B01001 variables.
#' @details [Formulas as documented by EPA were archived here](https://web.archive.org/web/20250118134239/https://www.epa.gov/system/files/documents/2024-07/ejscreen-tech-doc-version-2-3.pdf)
#' @seealso [tables_ejscreen_acs] [calc_ejam()] [acs_bybg()]
'formulas_ejscreen_acs'
