# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see
# EJAM/data-raw/datacreate_runtime_models.R

#' Regression models to predict runtime for ejamit by input type
#'
#' @name modelEjamitByAnalysisType
#' @docType data
#' @title Regression models to predict runtime for ejamit by input type
#' @description Weighted runtime models for point-buffer, FIPS, and shapefile ejamit analyses, fit from Analysis_timing_results*.csv files when scenario rows are available.
#' @details This list stores separate models for points, FIPS, shapefile, and available FIPS subtypes such as fips_city and fips_county. The points model uses input_number and radius when enough rows are available. FIPS and shapefile models use input_number because there is no point-buffer radius in those workflows. Missing scenario models are stored as NULL until timing rows for that scenario have been collected.
"modelEjamitByAnalysisType"
