#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_tables_ejscreen_acs.R or similar files

#' @name tables_ejscreen_acs
#' @docType data
#' @title tables_ejscreen_acs dataset
#' @details See
#'
#'  ```
#'  yr = 2023
#'  urls = paste0('https://data.census.gov/table/ACSDT5Y', yr, '.', tables_ejscreen_acs)
#'  sapply(urls, browseURL)
#'  acsinfo <- tidycensus::load_variables(acs_endyear(guess_census_has_published = TRUE), 'acs5')
#' ```
#'
#' Notes:
#'
#'  - B25034  pre1960, for lead paint indicator (environmental not demographic per se)
#'  - B01001  sex and age / basic population counts
#'  - B03002  race with hispanic ethnicity
#'  - B02001  race without hispanic ethnicity
#'  - B15002  education
#'  - B23025  unemployed
#'  - C17002  low income, poor, etc.
#'  - B19301  per capita income
#'  - B25032  owned units vs rented units (occupied housing units, same universe as B25003)
#'  - B28003  no broadband
#'  - B27010  no health insurance
#'  - C16002  (language category and) % of households limited English speaking (lingiso) <https://data.census.gov/table/ACSDT5Y2023.C16002>
#'  - B16004  (language category and) % of residents (not hhlds) speak no English at all <https://data.census.gov/table/ACSDT5Y2023.B16004>
#'
#'  TRACT ONLY, but also used by EJSCREEN:
#'  - C16001   languages detailed list: % of residents (not hhlds) IN TRACT speak Chinese, etc. <https://data.census.gov/table/ACSDT5Y2023.C16001>
#'  - B18101   disability
#' @seealso [formulas_ejscreen_acs]
'tables_ejscreen_acs'
