#' Expanded report metadata name-list data objects
#'
#' @docType data
#' @name names_report_ratio_metadata
#' @aliases names_age_avg
#' @aliases names_age_pctile
#' @aliases names_age_ratio_to_avg
#' @aliases names_age_ratio_to_state_avg
#' @aliases names_age_state_avg
#' @aliases names_age_state_pctile
#' @aliases names_climate_ratio_to_avg
#' @aliases names_climate_ratio_to_state_avg
#' @aliases names_community_avg
#' @aliases names_community_pctile
#' @aliases names_community_ratio_to_avg
#' @aliases names_community_ratio_to_state_avg
#' @aliases names_community_state_avg
#' @aliases names_community_state_pctile
#' @aliases names_criticalservice_ratio_to_avg
#' @aliases names_criticalservice_ratio_to_state_avg
#' @aliases names_d_extra_avg
#' @aliases names_d_extra_pctile
#' @aliases names_d_extra_ratio_to_avg
#' @aliases names_d_extra_ratio_to_state_avg
#' @aliases names_d_extra_state_avg
#' @aliases names_d_extra_state_pctile
#' @aliases names_d_language_avg
#' @aliases names_d_language_pctile
#' @aliases names_d_language_ratio_to_avg
#' @aliases names_d_language_ratio_to_state_avg
#' @aliases names_d_language_state_avg
#' @aliases names_d_language_state_pctile
#' @aliases names_d_languageli_avg
#' @aliases names_d_languageli_pctile
#' @aliases names_d_languageli_ratio_to_avg
#' @aliases names_d_languageli_ratio_to_state_avg
#' @aliases names_d_languageli_state_avg
#' @aliases names_d_languageli_state_pctile
#' @title Expanded report metadata name-list data objects
#' @description Character vectors of indicator names generated from the
#'   `varlist` column in [map_headernames]. These lists support expanded
#'   average, percentile, and ratio-to-average metadata for community report
#'   rows.
#' @details These objects are generated by
#'   `data-raw/datacreate_names_of_indicators.R` from `map_headernames.csv`.
#'   They are intentionally grouped here because they are internal helper lists
#'   rather than separate user-facing datasets.
#' @seealso [map_headernames] [varlist2names()] [names_d] [names_e]
#' @keywords internal
NULL
