# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see
# EJAM/data-raw/datacreate_runtime_models.R

#' Regression models to predict runtime for ejamit by input type
#'
#' @name modelEjamitByAnalysisType
#' @docType data
#' @title Regression models to predict runtime for ejamit by input type
#' @description Weighted runtime models for point-buffer, FIPS, and shapefile ejamit analyses, fit from Analysis_timing_results*.csv files when scenario rows are available.
#' @details This list stores legacy fallback models for points, FIPS, shapefile, and available FIPS subtypes such as fips_city and fips_county. Current live web estimates use measured profiles in utils_speedtest.R instead. The fallback FIPS and shapefile models use input_number only and do not model an optional buffer radius.
"modelEjamitByAnalysisType"
